// SPDX-License-Identifier: MIT
pragma solidity ^0.8.23;

import {Test} from "forge-std/Test.sol";
import {stdJson} from "forge-std/StdJson.sol";
import {CredentialAnchor} from "../contracts/CredentialAnchor.sol";
import {PolicyRegistry} from "../contracts/PolicyRegistry.sol";
import {NullifierRegistry} from "../contracts/NullifierRegistry.sol";
import {PredicateVerifier} from "../contracts/PredicateVerifier.sol";
import {AgentAccessGate} from "../contracts/AgentAccessGate.sol";
import {Groth16CircuitVerifier} from "../contracts/Groth16CircuitVerifier.sol";

/// End-to-end tests against a REAL Groth16 proof (test/fixtures/presentation.json,
/// generated by the circuits package from the parity fixture — no mock proofs
/// anywhere, the anti-sentinel rule). The fixture pins the PredicateVerifier
/// address (contextHash binding), so we deployCodeTo that exact address.
contract ActaE2ETest is Test {
    using stdJson for string;

    // must match gen-contract-fixture.js
    address constant VERIFIER_ADDR = 0x00000000000000000000000000000000aC7A0001;
    address constant ISSUER_ADDR = 0x0000000000000000000000000000000015540001;

    CredentialAnchor anchor;
    PolicyRegistry policies;
    NullifierRegistry nullifiers;
    PredicateVerifier verifier;
    Groth16CircuitVerifier circuitVerifier;
    AgentAccessGate gate;

    uint256[2] a;
    uint256[2][2] b;
    uint256[2] c;
    uint256[8] signals;
    uint256 policyId;
    uint256 currentTime;

    function setUp() public {
        string memory json = vm.readFile("test/fixtures/presentation.json");

        anchor = new CredentialAnchor();
        policies = new PolicyRegistry();
        nullifiers = new NullifierRegistry();
        deployCodeTo(
            "PredicateVerifier.sol:PredicateVerifier",
            abi.encode(policies, anchor, nullifiers),
            VERIFIER_ADDR
        );
        verifier = PredicateVerifier(VERIFIER_ADDR);
        nullifiers.setVerifier(VERIFIER_ADDR);
        circuitVerifier = new Groth16CircuitVerifier();

        // issuer anchors the fixture's anonymity set, in order
        uint256[] memory leaves = json.readUintArray(".anchorLeaves");
        vm.startPrank(ISSUER_ADDR);
        for (uint256 i = 0; i < leaves.length; i++) {
            anchor.anchor(leaves[i]);
        }
        vm.stopPrank();

        // register the policy
        PolicyRegistry.Policy memory p;
        p.predicateHash = json.readUint(".policy.predicateHash");
        p.issuerKeyHash = json.readUint(".policy.issuerKeyHash");
        p.issuer = ISSUER_ADDR;
        p.sanctionsRoot = json.readUint(".policy.sanctionsRoot");
        p.circuitVerifier = address(circuitVerifier);
        p.uri = "auditScore >= 80 AND jurisdiction not in OFAC (demo)";
        uint256[] memory pc = json.readUintArray(".policy.predClaimRef");
        uint256[] memory po = json.readUintArray(".policy.predOp");
        uint256[] memory pv = json.readUintArray(".policy.predValue");
        uint256[] memory tt = json.readUintArray(".policy.tokType");
        uint256[] memory ta = json.readUintArray(".policy.tokArg");
        for (uint256 i = 0; i < 4; i++) {
            p.predClaimRef[i] = pc[i];
            p.predOp[i] = po[i];
            p.predValue[i] = pv[i];
        }
        for (uint256 i = 0; i < 16; i++) {
            p.tokType[i] = tt[i];
            p.tokArg[i] = ta[i];
        }
        policyId = policies.registerPolicy(p);
        assertEq(policyId, json.readUint(".policyId"));

        gate = new AgentAccessGate(verifier, policyId);

        // proof + signals
        uint256[] memory aj = json.readUintArray(".a");
        uint256[] memory bj = json.readUintArray(".b");
        uint256[] memory cj = json.readUintArray(".c");
        uint256[] memory sj = json.readUintArray(".signals");
        a = [aj[0], aj[1]];
        b = [[bj[0], bj[1]], [bj[2], bj[3]]];
        c = [cj[0], cj[1]];
        for (uint256 i = 0; i < 8; i++) {
            signals[i] = sj[i];
        }

        currentTime = json.readUint(".currentTime");
        vm.warp(currentTime);
    }

    function test_OnChainLeanIMTMatchesCircuitRoot() public view {
        // cross-implementation parity: poseidon-solidity tree == zk-kit JS tree == circuit input
        assertEq(anchor.currentRoot(ISSUER_ADDR), signals[2]);
    }

    function test_HappyPath_GateEntry() public {
        uint256 nullifier = gate.enter(a, b, c, signals);
        assertEq(nullifier, signals[0]);
        assertGt(gate.entered(nullifier), 0);
        assertTrue(nullifiers.isAcceptedForPolicy(policyId, nullifier));
    }

    function test_Replay_Reverts() public {
        gate.enter(a, b, c, signals);
        vm.expectRevert(NullifierRegistry.NullifierAlreadyUsed.selector);
        gate.enter(a, b, c, signals);
    }

    function test_TamperedSignal_Reverts() public {
        uint256[8] memory bad = signals;
        bad[7] = bad[7] + 1; // different sessionNonce than proven
        vm.expectRevert(PredicateVerifier.InvalidProof.selector);
        verifier.verifyPresentation(policyId, a, b, c, bad);
    }

    function test_TamperedProof_Reverts() public {
        uint256[2] memory badA = a;
        badA[0] = badA[0] + 1;
        vm.expectRevert(); // pairing precompile failure or InvalidProof
        verifier.verifyPresentation(policyId, badA, b, c, signals);
    }

    function test_WrongPolicyBinding_Reverts() public {
        // a second policy with a different predicate hash: the same proof must not transfer
        PolicyRegistry.Policy memory p2;
        p2.predicateHash = signals[4] + 1;
        p2.issuerKeyHash = signals[1];
        p2.issuer = ISSUER_ADDR;
        p2.sanctionsRoot = signals[3];
        p2.circuitVerifier = address(circuitVerifier);
        uint256 pid2 = policies.registerPolicy(p2);
        vm.expectRevert(PredicateVerifier.PredicateHashMismatch.selector);
        verifier.verifyPresentation(pid2, a, b, c, signals);
    }

    function test_WrongIssuer_Reverts() public {
        PolicyRegistry.Policy memory p3;
        p3.predicateHash = signals[4];
        p3.issuerKeyHash = signals[1] + 1; // different trusted issuer key
        p3.issuer = ISSUER_ADDR;
        p3.sanctionsRoot = signals[3];
        p3.circuitVerifier = address(circuitVerifier);
        uint256 pid3 = policies.registerPolicy(p3);
        vm.expectRevert(PredicateVerifier.IssuerMismatch.selector);
        verifier.verifyPresentation(pid3, a, b, c, signals);
    }

    function test_UnknownAnchorRoot_Reverts() public {
        PolicyRegistry.Policy memory p4;
        p4.predicateHash = signals[4];
        p4.issuerKeyHash = signals[1];
        p4.issuer = address(0xDEAD); // issuer with no anchored tree
        p4.sanctionsRoot = signals[3];
        p4.circuitVerifier = address(circuitVerifier);
        uint256 pid4 = policies.registerPolicy(p4);
        // note: contextHash check happens after root check in the sequence
        vm.expectRevert(PredicateVerifier.UnknownAnchorRoot.selector);
        verifier.verifyPresentation(pid4, a, b, c, signals);
    }

    function test_StaleTimestamp_Reverts() public {
        vm.warp(currentTime + 2 hours);
        vm.expectRevert(PredicateVerifier.StaleTimestamp.selector);
        verifier.verifyPresentation(policyId, a, b, c, signals);
    }

    function test_NullifierRegistry_OnlyVerifier() public {
        vm.expectRevert(NullifierRegistry.NotVerifier.selector);
        nullifiers.register(policyId, 123);
    }

    function test_Gas_HappyPath() public {
        uint256 g0 = gasleft();
        gate.enter(a, b, c, signals);
        uint256 used = g0 - gasleft();
        emit log_named_uint("gate.enter gas (verify + nullifier + event)", used);
        assertLt(used, 500_000);
    }
}
